spring.application.name=bike-theft-tracker
spring.config.import=optional:file:.env[.properties]
server.port=${SERVER_PORT}

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
cors.allow-credentials=${CORS_ALLOW_CREDENTIALS}
cors.allowed-methods=${CORS_ALLOWED_METHODS}
cors.allowed-headers=${CORS_ALLOWED_HEADERS}

spring.jpa.hibernate.ddl-auto=create-drop

# OpenAPI/Swagger UI
springdoc.swagger-ui.url=/openapi.yaml
# springdoc.api-docs.enabled=false